### PR TITLE
Verifying if cluster name already exists

### LINKED ISSUE #7: Check if a cluster exist by name before creating it
@mcruzdev if you want to do this one.. I will appreciate it... so I can have this logic in the library instead of the Zeebe Operator.. 

The CreateCluster function should receive a bool to check for an existing cluster with that name before creating it, something like

```
func CreateCluster(string name, bool checkIfExist ){

  if checkIfExist{
    GetAllClusters()
   // Check if a cluster exist with "name" 
  // if it exist, don't create
  // if it doesn't exist create
  }
  

}
```

### LINKED ISSUE #9: Implement method that gets cluster by name
This allows us to programatically get a cluster by name like:

```
func GetClusterByName(name string) or func GetClusterById(name string)
```

http://docs.camunda.io/docs/reference/cloud-console-api-reference/

### PR DESCRIPTION
**Pull request by mcruzdev**
This PR has been created from #7 issue

* Checkin if a cluster exists before creating it

* Has been created a file errors.go that help us to create custom erros on golang

### CODE REVIEW

**Comment by salaboy** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **salaboy**
You can assign the PR to them by writing `/assign @salaboy` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=salaboy%2Fcamunda-cloud-go-client).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/salaboy/camunda-cloud-go-client/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by salaboy** [comment]
@mcruzdev: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr | 8e8d4e43c4e62d8e3ac5ec417d41dfc459f26654 | [link](http://dashboard-jx.34.67.22.199.nip.io/namespaces/jx/pipelineruns/pr-q86nq) | `/test pr`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by mcruzdev** [comment]
#9 Method implemented

**Comment by salaboy** [comment]
@mcruzdev: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr | 220638657f320c5f55b0bafd82305866a7bc3360 | [link](http://dashboard-jx.34.67.22.199.nip.io/namespaces/jx/pipelineruns/pr-zzt9k) | `/test pr`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by salaboy** [comment]
merging now!

**Comment by salaboy** [comment]
@mcruzdev: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr | 1d023625d7e73405dc79a9b82acd4f8c5414dee1 | [link](http://dashboard-jx.34.67.22.199.nip.io/namespaces/jx/pipelineruns/pr-mffn7) | `/test pr`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Pull request merged**
