### PR TITLE
Add cobra CLI tool

### LINKED ISSUE #2: Add cobra to be CLI tool as well
@mcruzdev I think that having that in a separate repo is going to complicate things without a real reason, if you want to add cobra here, that will be welcome, as soon as the library is consumed by cobra and we can still call the library methods from the Operator that should be fine.

### PR DESCRIPTION
**Pull request by mcruzdev**
This is a draft PR from #2 issue

For now, we are using ` camunda-cloud-go-cli` to start the CLI tool, but on below examples I am using cc

I tested:
[cc] clusters get --all
[cc] clusters get --id
[cc] clusters get --params
[cc] clusters delete --id
[cc] clusters create --name 

* In main method `func main() {}`, I need to comment cmd.Execute()
```
func main() {
	http.HandleFunc("/", handler)
	http.ListenAndServe(":8080", nil)
	// cmd.Execute()
}
```

Next steps: 
* To adjust help `--help|-h` for clusters command 
* To validate clusters command args and flags
* Remove unnecessary login before each interation with Camunda API

### CODE REVIEW

**Comment by salaboy** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **salaboy**
You can assign the PR to them by writing `/assign @salaboy` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=salaboy%2Fcamunda-cloud-go-client).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/salaboy/camunda-cloud-go-client/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by salaboy** [comment]
@mcruzdev: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr | 761dceee41bb3a92060ab86c8f23879458377b90 | [link](http://dashboard-jx.34.67.22.199.nip.io/namespaces/jx/pipelineruns/pr-9lkwx) | `/test pr`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by salaboy** [comment]
@mcruzdev: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr | b745f052a01d4aa48d516a593f635a38f0621d28 | [link](http://dashboard-jx.34.67.22.199.nip.io/namespaces/jx/pipelineruns/pr-2ggp8) | `/test pr`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by salaboy** [comment]
@mcruzdev: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr | aabf9150e63fb10b6c9b76017b0ac6336d69455e | [link](http://dashboard-jx.34.67.22.199.nip.io/namespaces/jx/pipelineruns/pr-4qd9p) | `/test pr`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by mcruzdev** [comment]
@salaboy ,

Can you revise all texts?

I know that some texts are repeatable, but I think that for now it is not a big problem

We need to choose when the user will login on CLI

To test my changes, before each command I made a Login with Camunda Credentials

That way we gonna choose to authenticate the user? By env variables or flags on CLI statement( like --client-id --client-secret) ?

**Comment by salaboy** [comment]
@mcruzdev: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr | 6dd6f62858d01b2e72182273d7375e0cdedca689 | [link](http://dashboard-jx.34.67.22.199.nip.io/namespaces/jx/pipelineruns/pr-zlc6l) | `/test pr`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by salaboy** [comment]
@mcruzdev: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr | 87327132ce2fadf3a0427076070b84e05ef8ca44 | [link](http://dashboard-jx.34.67.22.199.nip.io/namespaces/jx/pipelineruns/pr-hft29) | `/test pr`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by salaboy** [comment]
@mcruzdev: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr | a25d2d2d12caa4bc2a384467dfaf25d15cae9a17 | [link](http://dashboard-jx.34.67.22.199.nip.io/namespaces/jx/pipelineruns/pr-tcl52) | `/test pr`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by salaboy** [comment]
@mcruzdev: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr | fd60a269ab7a790fed1d2d9a28111be49a1da9e7 | [link](http://dashboard-jx.34.67.22.199.nip.io/namespaces/jx/pipelineruns/pr-q99cv) | `/test pr`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by salaboy** [comment]
@mcruzdev I am merging to be able to move this repo to camunda cloud hub.. but notice that you included your credentials.. usually not recommended :)

**Pull request merged**
